#!/bin/bash

export DESKTOP_CORE_NAME="optimus"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v0.5.0-beta
export DESKTOP_CORE_ORG="Splode"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/optimus/releases/download"
