#!/bin/bash

export DESKTOP_CORE_NAME="optimus"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v0.5.0-beta
export DESKTOP_CORE_ORG="Splode"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/optimus/releases/download"

export DESKTOP_CORE_CHECKSUMS=(
  v0.5.0-beta#darwin#arm64#2078f0a72202341fd577a095a6c371e2d6c456b706eb8effc39505b18e3c0f8b
  v0.5.0-beta#darwin#amd64#2078f0a72202341fd577a095a6c371e2d6c456b706eb8effc39505b18e3c0f8b
)
